sc_sncn_ethercat: module_ethercat/src/foe.xc File Reference
foe.xc File Reference
header for file file over EtherCAT access.
#include <xs1.h>
#include <print.h>
#include "foe_chan.h"
#include "foefs.h"
#include "foe.h"
Functions
int foe_init (void)
int foe_close (void)
int foe_parse_packet (chanend foe_signal, uint16_t msg[], unsigned size)
Parse new packet.
unsigned foe_get_reply (uint16_t data[])
Get reply packet.
int foe_request (uint16_t data[])
int foe_file_access (chanend comm, int command)
This funciton is called by ecat_handler()
Detailed Description
header for file file over EtherCAT access.
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Frank Jeschke jesch.nosp@m.ke@f.nosp@m.jes.d.nosp@m.e
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file foe.xc.
Function Documentation
int foe_close (void)
Definition at line 144 of file foe.xc.
References foe_init().
int foe_file_access (chanend comm, int command)
This funciton is called by ecat_handler()
Here a channel commmunication abstraction is realized to allow applications to access the file within the filesystem without the need for shared memory.
See Also
foe_chan.h for a list of available channel commands
Parameters
command The command issued by the caller
comm the communication channel to transfer data forth and back.
0 on success, otherwise error.
Definition at line 398 of file foe.xc.
References BLKSZ, FOE_FILE_ACK, FOE_FILE_CLOSE, FOE_FILE_DATA, FOE_FILE_ERROR, FOE_FILE_FREE, FOE_FILE_OPEN, FOE_FILE_READ, FOE_FILE_SEEK, FOE_FILE_WRITE, foefs_close(), foefs_format(), foefs_open(), foefs_read(), foefs_seek(), MAX_FNAME, MODE_RW, and SEEK_SET.
unsigned foe_get_reply (uint16_t data[])
Get reply packet.
Parameters
data data field (16 bit)
Returns
word count of data field
Definition at line 341 of file foe.xc.
References foemsg_t::a, foemsg_t::b, foemsg_t::data, FOE_DATA_SIZE, foemsg_t::opcode, and foemsg_t::packetnumber.
int foe_init (void)
Definition at line 134 of file foe.xc.
References FOE_STATE_IDLE, and state.
Referenced by foe_close().
int foe_parse_packet (chanend foe_signal, uint16_t msg[], unsigned size)
Parse new packet.
Parameters
msg the message to parse
Returns
0 no error, 1 no error, reply pending, <0 error
Definition at line 150 of file foe.xc.
References foemsg_t::a, foemsg_t::b, foemsg_t::data, foemsg_t::filename, FOE_ACK, FOE_DATA, FOE_DATA_SIZE, FOE_ERR_DISKFULL, FOE_ERR_ILLEGAL, FOE_ERR_NOTFOUND, FOE_ERR_UNDEF, FOE_ERROR, FOE_FILE_READY, FOE_HEADER_SIZE, FOE_MAX_MSGSIZE, FOE_READ, FOE_STATE_COMMIT, FOE_STATE_IDLE, FOE_STATE_READ, FOE_STATE_REQUEST, FOE_STATE_WRITE, FOE_UNUSED, FOE_WRITE, foefs_close(), foefs_free(), foefs_open(), foefs_read(), foefs_write(), MODE_RO, MODE_RW, foemsg_t::opcode, foemsg_t::packetnumber, and state.
int foe_request (uint16_t data[])
Definition at line 359 of file foe.xc.
References foemsg_t::a, foemsg_t::b, COMMIT_FILE, foemsg_t::filename, FOE_DATA_SIZE, FOE_READ, FOE_STATE_COMMIT, FOE_STATE_IDLE, FOE_STATE_REQUEST, FOE_WRITE, foefs_open(), MODE_RO, MODE_RW, foemsg_t::opcode, foemsg_t::password, REQUEST_FILE, and state.