sc_sncn_motoctrl_sin: sc_sncn_motorctrl_sin/module_blocks/src/util/arctan.xc File Reference
arctan.xc File Reference
#include "sine_table_big.h"
#include <print.h>
Macros
#define COMMUTATION 1
#define SINE_TABLE 2
#define defFactor 65536/64
Functions
int arctg1 (int Real, int Imag)
int sine_expanded (int angle, int select_mode)
int sine_third_expanded (int angle)
int sine_table_expanded (int angle)
Detailed Description
Arc tangent calculations
Copyright (c) 2014, Synapticon GmbH All rights reserved. Authors: Ludwig Orgler lorgl.nosp@m.er@s.nosp@m.ynapt.nosp@m.icon.nosp@m..com & Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file arctan.xc.
Macro Definition Documentation
#define COMMUTATION 1
Definition at line 43 of file arctan.xc.
Referenced by sine_expanded(), and sine_third_expanded().
#define defFactor 65536/64
Referenced by arctg1().
#define SINE_TABLE 2
Definition at line 44 of file arctan.xc.
Referenced by sine_expanded(), and sine_table_expanded().
Function Documentation
int arctg1 (int Real, int Imag)
Definition at line 46 of file arctan.xc.
References arctg_table, and defFactor.
int sine_expanded (int angle, int select_mode)
Definition at line 103 of file arctan.xc.
References COMMUTATION, SINE_TABLE, sine_table, and sine_third.
Referenced by sine_table_expanded(), and sine_third_expanded().
int sine_table_expanded (int angle)
Definition at line 177 of file arctan.xc.
References sine_expanded(), and SINE_TABLE.
Referenced by _torque_ctrl().
int sine_third_expanded (int angle)
Definition at line 172 of file arctan.xc.
References COMMUTATION, and sine_expanded().
Referenced by commutation_sinusoidal_loop().