sc_sncn_ethercat: module_ethercat/src/foefs.h File Reference
foefs.h File Reference
API for simple and specialized filesystem for use within the EtherCAT module.
Data Structures
struct foefile_t
Filesystem entry.
Macros
#define BLKSZ 2400
#define MAX_FNAME 10
#define SEEK_SET 0
#define SEEK_CUR 1
#define MODE_RO 0
#define MODE_RW 1
#define REQUEST_FILE 1
request file from ethercat master
#define COMMIT_FILE 2
push file to ehtercat master
Functions
int foefs_open (char filename[], int mode)
open file
int foefs_close (int fh)
close file handle
int foefs_read (int fh, int size, char b[])
read from file handle
int foefs_write (int fh, int size, char b[])
write bytes to file starting at offset
int foefs_seek (int fh, int offset, int whence)
set file position
int foefs_init (void)
init pseudo filesystem
int foefs_release (void)
release pseude filesystem
int foefs_format (void)
format file system
int foefs_free (void)
Request the number of free bytes.
Detailed Description
API for simple and specialized filesystem for use within the EtherCAT module.
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Frank Jeschke jesch.nosp@m.ke@f.nosp@m.jes.d.nosp@m.e
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file foefs.h.
Macro Definition Documentation
#define BLKSZ 2400
Definition at line 44 of file foefs.h.
Referenced by foe_file_access(), and foefs_write().
#define COMMIT_FILE 2
push file to ehtercat master
Definition at line 52 of file foefs.h.
Referenced by foe_request().
#define MAX_FNAME 10
Definition at line 45 of file foefs.h.
Referenced by foe_file_access(), foefs_open(), and foefs_remove().
#define MODE_RO 0
Definition at line 48 of file foefs.h.
Referenced by foe_parse_packet(), foe_request(), foefs_open(), and foefs_write().
#define MODE_RW 1
Definition at line 49 of file foefs.h.
Referenced by foe_file_access(), foe_parse_packet(), foe_request(), and foefs_open().
#define REQUEST_FILE 1
request file from ethercat master
Definition at line 51 of file foefs.h.
Referenced by foe_request().
#define SEEK_CUR 1
Definition at line 47 of file foefs.h.
Referenced by foefs_seek().
#define SEEK_SET 0
Definition at line 46 of file foefs.h.
Referenced by foe_file_access(), and foefs_seek().
Function Documentation
int foefs_close (int fh)
close file handle
Parameters
fh file handle to close
Returns
0 on success, <0 otherwise
Definition at line 92 of file foefs.xc.
References foefile_t::currentpos, and foefile_t::fh.
Referenced by foe_file_access(), and foe_parse_packet().
int foefs_format (void)
format file system
this is basically a reinitalize.
Returns
0 on success
Definition at line 192 of file foefs.xc.
References foefs_init().
Referenced by foe_file_access().
int foefs_free (void)
Request the number of free bytes.
Returns
Number of available bytes.
Definition at line 213 of file foefs.xc.
References freespace.
Referenced by foe_parse_packet().
int foefs_init (void)
init pseudo filesystem
Returns
0 on success
Definition at line 176 of file foefs.xc.
References foefile_t::fh, freespace, foefile_t::name, and foefile_t::size.
Referenced by foefs_format().
int foefs_open (char filename[], int mode)
open file
Parameters
filename filename to open
Returns
file handle, <0 on error
Definition at line 66 of file foefs.xc.
References foefile_t::currentpos, foefile_t::fh, FOE_ERR_NOTFOUND, FOE_ERR_PERM, freespace, MAX_FNAME, foefile_t::mode, MODE_RO, MODE_RW, and foefile_t::name.
Referenced by foe_file_access(), foe_parse_packet(), and foe_request().
int foefs_read (int fh, int size, char b[])
read from file handle
Parameters
fh file handle to read from
size number of byes to read
b[] buffer to store read bytes
Returns
number of bytes read, <0 on error
Definition at line 99 of file foefs.xc.
References foefile_t::bytes, foefile_t::currentpos, foefile_t::fh, FOE_ERR_NOACCESS, and foefile_t::size.
Referenced by foe_file_access(), and foe_parse_packet().
int foefs_release (void)
release pseude filesystem
Returns
0 on success
Definition at line 187 of file foefs.xc.
int foefs_seek (int fh, int offset, int whence)
set file position
Parameters
fh filehandle to operate on
offset new offset of filehandle
where either SEEK_SET for absolute positioning or SEEK_CUR for relative positioning.
0 on success
Definition at line 155 of file foefs.xc.
References foefile_t::currentpos, foefile_t::fh, FOE_ERR_NOACCESS, SEEK_CUR, and SEEK_SET.
Referenced by foe_file_access().
int foefs_write (int fh, int size, char b[])
write bytes to file starting at offset
Parameters
fh filehandle to write to
size number of bytes to write
b[] buffer holding bytes to write
Returns
number of bytes written, <0 on error
Definition at line 127 of file foefs.xc.
References BLKSZ, foefile_t::bytes, foefile_t::currentpos, foefile_t::fh, FOE_ERR_ILLEGAL, FOE_ERR_NOACCESS, FOE_ERR_PERM, freespace, foefile_t::mode, MODE_RO, and foefile_t::size.
Referenced by foe_parse_packet().