sc_sncn_ethercat: app_linux_igh-master-example/main.c File Reference
main.c File Reference
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <sys/resource.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdarg.h>
#include "ecrt.h"
Macros
#define MAJOR 1
#define MINOR 0
#define MAXDBGLVL 3
#define FREQUENCY 100
#define PRIORITY 1
#define CONFIGURE_PDOS 1
#define SDO_ACCESS 1
#define CIA402 1
#define SomanetPos 0, 0
#define SOMANET_ID 0x000022d2, 0x00000201
#define CAN_OD_CONTROL_WORD 0x6040 /* RX; 8 bit */
#define CAN_OD_STATUS_WORD 0x6041 /* TX; 8 bit */
#define CAN_OD_MODES 0x6060 /* RX; 8 bit */
#define CAN_OD_MODES_DISP 0x6061 /* TX; 8 bit */
#define CAN_OD_POS_VALUE 0x6064 /* TX; 32 bit */
#define CAN_OD_POS_TARGET 0x607A /* RX; 32 bit */
#define CAN_OD_VEL_VALUE 0x606C /* TX; 32 bit */
#define CAN_OD_VEL_TARGET 0x60ff /* RX; 32 bit */
#define CAN_OD_TOR_VALUE 0x6077 /* TX; 16 bit */
#define CAN_OD_TOR_TARGET 0x6071 /* RX; 16 bit */
#define STATUSW1 0x88AA
#define STATUSW2 0xAA88
#define OPMODES1 0xf1
#define OPMODES2 0x1f
#define TORVAL1 0xabab
#define TORVAL2 0xbaba
#define VELVAL1 0x2d2d4d4d
#define VELVAL2 0xd4d4d2d2
#define POSVAL1 0xe4e4e2e2
#define POSVAL2 0x2e2e4e4e
Functions
void check_domain1_state (void)
void check_master_state (void)
void check_slave_config_states (void)
void read_sdo (ec_sdo_request_t *req)
void write_sdo (ec_sdo_request_t *req, unsigned data)
void cyclic_task ()
void signal_handler (int signum)
int main (int argc, char **argv)
Variables
ec_pdo_entry_info_t slave_0_pdo_entries []
ec_pdo_info_t slave_0_pdos []
ec_sync_info_t slave_0_syncs []
Macro Definition Documentation
#define CAN_OD_CONTROL_WORD 0x6040 /* RX; 8 bit */
Definition at line 169 of file main.c.
#define CAN_OD_MODES 0x6060 /* RX; 8 bit */
Definition at line 171 of file main.c.
Referenced by main().
#define CAN_OD_MODES_DISP 0x6061 /* TX; 8 bit */
Definition at line 172 of file main.c.
#define CAN_OD_POS_TARGET 0x607A /* RX; 32 bit */
Definition at line 175 of file main.c.
#define CAN_OD_POS_VALUE 0x6064 /* TX; 32 bit */
Definition at line 174 of file main.c.
Referenced by main().
#define CAN_OD_STATUS_WORD 0x6041 /* TX; 8 bit */
Definition at line 170 of file main.c.
#define CAN_OD_TOR_TARGET 0x6071 /* RX; 16 bit */
Definition at line 179 of file main.c.
#define CAN_OD_TOR_VALUE 0x6077 /* TX; 16 bit */
Definition at line 178 of file main.c.
Referenced by main().
#define CAN_OD_VEL_TARGET 0x60ff /* RX; 32 bit */
Definition at line 177 of file main.c.
#define CAN_OD_VEL_VALUE 0x606C /* TX; 32 bit */
Definition at line 176 of file main.c.
Referenced by main().
#define CIA402 1
Definition at line 94 of file main.c.
#define CONFIGURE_PDOS 1
Definition at line 92 of file main.c.
#define FREQUENCY 100
Definition at line 88 of file main.c.
Referenced by cyclic_task(), and main().
#define MAJOR 1
Definition at line 82 of file main.c.
#define MAXDBGLVL 3
Definition at line 85 of file main.c.
#define MINOR 0
Definition at line 83 of file main.c.
#define OPMODES1 0xf1
Referenced by cyclic_task().
#define OPMODES2 0x1f
Referenced by cyclic_task().
#define POSVAL1 0xe4e4e2e2
Referenced by cyclic_task().
#define POSVAL2 0x2e2e4e4e
Referenced by cyclic_task().
#define PRIORITY 1
Definition at line 89 of file main.c.
#define SDO_ACCESS 1
Definition at line 93 of file main.c.
#define SOMANET_ID 0x000022d2, 0x00000201
Definition at line 125 of file main.c.
Referenced by main().
#define SomanetPos 0, 0
Definition at line 124 of file main.c.
Referenced by main().
#define STATUSW1 0x88AA
Referenced by cyclic_task().
#define STATUSW2 0xAA88
Referenced by cyclic_task().
#define TORVAL1 0xabab
Referenced by cyclic_task().
#define TORVAL2 0xbaba
Referenced by cyclic_task().
#define VELVAL1 0x2d2d4d4d
Referenced by cyclic_task().
#define VELVAL2 0xd4d4d2d2
Referenced by cyclic_task().
Function Documentation
void check_domain1_state (void)
Definition at line 304 of file main.c.
Referenced by cyclic_task().
void check_master_state (void)
Definition at line 320 of file main.c.
Referenced by cyclic_task().
void check_slave_config_states (void)
Definition at line 338 of file main.c.
Referenced by cyclic_task().
void cyclic_task ()
Definition at line 404 of file main.c.
References check_domain1_state(), check_master_state(), check_slave_config_states(), FREQUENCY, OPMODES1, OPMODES2, POSVAL1, POSVAL2, read_sdo(), STATUSW1, STATUSW2, TORVAL1, TORVAL2, VELVAL1, VELVAL2, and write_sdo().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 579 of file main.c.
References CAN_OD_MODES, CAN_OD_POS_VALUE, CAN_OD_TOR_VALUE, CAN_OD_VEL_VALUE, cyclic_task(), FREQUENCY, signal_handler(), slave_0_syncs, SOMANET_ID, and SomanetPos.
void read_sdo (ec_sdo_request_t * req)
Definition at line 358 of file main.c.
Referenced by cyclic_task().
void signal_handler (int signum)
Definition at line 497 of file main.c.
Referenced by main().
void write_sdo (ec_sdo_request_t * req, unsigned data)
Definition at line 379 of file main.c.
Referenced by cyclic_task().
Variable Documentation
ec_pdo_entry_info_t slave_0_pdo_entries[]
Initial value:
= {
    {0x6040, 0x00, 16},
    {0x6060, 0x00, 8},
    {0x6071, 0x00, 16},
    {0x607a, 0x00, 32},
    {0x60ff, 0x00, 32},
    {0x6041, 0x00, 16},
    {0x6061, 0x00, 8},
    {0x6064, 0x00, 32},
    {0x606c, 0x00, 32},
    {0x6077, 0x00, 16},
}
Definition at line 226 of file main.c.
ec_pdo_info_t slave_0_pdos[]
Initial value:
= {
    {0x1600, 5, slave_0_pdo_entries + 0},
    {0x1a00, 5, slave_0_pdo_entries + 5},
}
Definition at line 239 of file main.c.
ec_sync_info_t slave_0_syncs[]
Initial value:
= {
    {0, EC_DIR_OUTPUT, 0, NULL, EC_WD_DISABLE},
    {1, EC_DIR_INPUT, 0, NULL, EC_WD_DISABLE},
    {2, EC_DIR_OUTPUT, 1, slave_0_pdos + 0, EC_WD_DISABLE},
    {3, EC_DIR_INPUT, 1, slave_0_pdos + 1, EC_WD_DISABLE},
    {0xff}
}
Definition at line 244 of file main.c.
Referenced by main().