sc_sncn_ethercat: app_simple-webserver/src/webs.xc File Reference
webs.xc File Reference
#include <xs1.h>
#include <xclib.h>
#include <platform.h>
#include <print.h>
#include "xtcp.h"
#include "uip_server.h"
#include "xhttpd.h"
#include <otp_board_info.h>
#include "ethercat.h"
Macros
#define MAX_BUFFER_SIZE 1024
Functions
int main (void)
Variables
xtcp_ipconfig_t ipconfig
Macro Definition Documentation
#define MAX_BUFFER_SIZE 1024
Definition at line 35 of file webs.xc.
Function Documentation
int main (void)
< CAN from module_ethercat to consumer
< CAN from consumer to module_ethercat
< Ethernet from module_ethercat to consumer
< Ethernet from consumer to module_ethercat
< Signals from EtherCAT to Ethernet MII
< File from module_ethercat to consumer
< File from consumer to module_ethercat
Definition at line 112 of file webs.xc.
References ecat_handler(), ecat_init(), ipconfig, stdcore, and xhttpd().
Variable Documentation
xtcp_ipconfig_t ipconfig
Initial value:
= {
                { 192,168,0,23 },
                { 255,255,255,0 },
                { 192,168,0,1 }
}
Definition at line 19 of file webs.xc.
Referenced by main().