sc_sncn_motoctrl_sin: sc_sncn_motorctrl_sin/module_ctrl_loops/velocity/velocity_ctrl_server.xc File Reference
velocity_ctrl_server.xc File Reference
#include "velocity_ctrl_server.h"
#include "refclk.h"
#include "qei_client.h"
#include "hall_client.h"
#include "comm_loop_client.h"
#include "filter_blocks.h"
#include <xscope.h>
#include <internal_config.h>
#include <drive_config.h>
#include "print.h"
Functions
void velocity_control (ctrl_par &velocity_ctrl_params, filter_par &sensor_filter_params, hall_par &hall_params, qei_par &qei_params, int sensor_used, chanend c_hall, chanend c_qei, chanend c_velocity_ctrl, chanend c_commutation)
Velocity Control Loop.
Detailed Description
Velocity Control Loop Server
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file velocity_ctrl_server.xc.
Function Documentation
void velocity_control (ctrl_par & velocity_ctrl_params, filter_par & sensor_filter_params, hall_par & hall_params, qei_par & qei_params, int sensor_used, chanend c_hall, chanend c_qei, chanend c_velocity_ctrl, chanend c_commutation)
Velocity Control Loop.
Input
Parameters
velocity_ctrl_params struct defines the velocity control parameters
sensor_filter_par struct defines the filter parameters
hall_params struct defines the poles for hall sensor and gear-ratio
qei_params struct defines the resolution for qei sensor and gear-ratio
sensor_used specify the sensors to used via HALL/QEI defines
Input Channel c_hall channel to receive position information from hall c_qei channel to receive position information from qei c_velocity_ctrl channel to receive/send velocity control information
Output Channel c_commutation channel to send motor voltage input value
Definition at line 54 of file velocity_ctrl_server.xc.
References __check_commutation_init(), CHECK_BUSY, S_Control::Control_limit, ENABLE_VELOCITY_CTRL, filter(), S_Filter_length::filter_length, FILTER_SIZE_MAX, S_QEI::gear_ratio, S_Hall::gear_ratio, GET_VELOCITY_TOKEN, HALL, S_QEI::index, INIT, INIT_BUSY, init_filter(), init_state(), S_Control::Integral_limit, S_Control::Kd_d, S_Control::Kd_n, S_Control::Ki_d, S_Control::Ki_n, S_Control::Kp_d, S_Control::Kp_n, S_Control::Loop_time, S_QEI::max_count, MSEC_STD, S_Hall::pole_pairs, S_QEI::poles, QEI, S_QEI::real_counts, SENSOR_SELECT, SET, set_commutation_sinusoidal(), SET_CTRL_PARAMETER, SET_VELOCITY_CTRL_HALL, SET_VELOCITY_CTRL_QEI, SET_VELOCITY_FILTER, SET_VELOCITY_TOKEN, SHUTDOWN_VELOCITY_CTRL, UNSET, VELOCITY_CTRL_READ, VELOCITY_CTRL_STATUS, and VELOCITY_CTRL_WRITE.
Referenced by main().