sc_sncn_ethercat: app_simple-webserver/src/httpd.c File Reference
httpd.c File Reference
#include <string.h>
#include <print.h>
#include "xtcp_client.h"
#include "httpd.h"
Data Structures
struct httpd_state_t
Macros
#define NUM_HTTPD_CONNECTIONS 10
Typedefs
typedef struct httpd_state_t httpd_state_t
Functions
void httpd_init (chanend tcp_svr)
void parse_http_request (httpd_state_t *hs, char *data, int len)
void httpd_recv (chanend tcp_svr, xtcp_connection_t *conn)
void httpd_send (chanend tcp_svr, xtcp_connection_t *conn)
void httpd_init_state (chanend tcp_svr, xtcp_connection_t *conn)
void httpd_free_state (xtcp_connection_t *conn)
void httpd_handle_event (chanend tcp_svr, xtcp_connection_t *conn)
Variables
char page []
httpd_state_t connection_states [NUM_HTTPD_CONNECTIONS]
Macro Definition Documentation
#define NUM_HTTPD_CONNECTIONS 10
Definition at line 20 of file httpd.c.
Referenced by httpd_free_state(), httpd_init(), and httpd_init_state().
Typedef Documentation
typedef struct httpd_state_t httpd_state_t
Function Documentation
void httpd_free_state (xtcp_connection_t * conn)
Definition at line 174 of file httpd.c.
References httpd_state_t::active, httpd_state_t::conn_id, and NUM_HTTPD_CONNECTIONS.
Referenced by httpd_handle_event().
void httpd_handle_event (chanend tcp_svr, xtcp_connection_t * conn)
Definition at line 190 of file httpd.c.
References httpd_free_state(), httpd_init_state(), httpd_recv(), and httpd_send().
Referenced by xhttpd().
void httpd_init (chanend tcp_svr)
Definition at line 37 of file httpd.c.
References httpd_state_t::active, httpd_state_t::dptr, and NUM_HTTPD_CONNECTIONS.
Referenced by xhttpd().
void httpd_init_state (chanend tcp_svr, xtcp_connection_t * conn)
Definition at line 143 of file httpd.c.
References httpd_state_t::active, httpd_state_t::conn_id, httpd_state_t::dptr, and NUM_HTTPD_CONNECTIONS.
Referenced by httpd_handle_event().
void httpd_recv (chanend tcp_svr, xtcp_connection_t * conn)
Definition at line 75 of file httpd.c.
References httpd_state_t::dptr, and parse_http_request().
Referenced by httpd_handle_event().
void httpd_send (chanend tcp_svr, xtcp_connection_t * conn)
Definition at line 106 of file httpd.c.
References httpd_state_t::dlen, httpd_state_t::dptr, and httpd_state_t::prev_dptr.
Referenced by httpd_handle_event().
void parse_http_request (httpd_state_t * hs, char * data, int len)
Definition at line 52 of file httpd.c.
References httpd_state_t::dlen, httpd_state_t::dptr, and page.
Referenced by httpd_recv().
Variable Documentation
httpd_state_t connection_states[NUM_HTTPD_CONNECTIONS]
Definition at line 33 of file httpd.c.
char page[]
Initial value:
=       "HTTP/1.0 200 OK\nServer: xc2/pre-1.0 (http://xmos.com)\nContent-type: text/html\n\n"
                                "<!DOCTYPE html>\n"
                                "<html><head><title>Hello world</title></head>\n"
                                "<body>Hello World!</body></html>"
Definition at line 13 of file httpd.c.
Referenced by parse_http_request().