sc_sncn_motoctrl_sin: sc_sncn_motorctrl_sin/module_qei/src/qei_client.h File Reference
qei_client.h File Reference
#include <bldc_motor_config.h>
#include "filter_blocks.h"
#include <print.h>
#include <xs1.h>
#include <stdio.h>
#include "qei_config.h"
Data Structures
struct QEI_VELOCITY_PARAM
Get position from QEI Server.
Typedefs
typedef struct QEI_VELOCITY_PARAM qei_velocity_par {int, int} get_qei_position_absolute(chanend c_qei)
Get position from QEI Server.
Functions
void init_qei_velocity_params (qei_velocity_par &qei_velocity_params)
Initialize struct for velocity calculation from QEI sensor.
int get_qei_velocity (chanend c_qei, qei_par &qei_params, qei_velocity_par &qei_velocity_params)
Calculates the velocity from QEI sensor in 1 ms loop.
int __qei_max_counts (int real_counts)
Internal function to calculate QEI position information.
void set_qei_sync_offset (chanend c_qei, int offset_forward, int offset_backward)
Internal function.
Detailed Description
QEI Sensor Client Functions
Copyright (c) 2014, Synapticon GmbH & XMOS Ltd All rights reserved. Authors: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com & Martin Schwarz mschw.nosp@m.arz@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file qei_client.h.
Typedef Documentation
typedef struct QEI_VELOCITY_PARAM qei_velocity_par {int, int} get_qei_position_absolute(chanend c_qei)
Get position from QEI Server.
Output channel c_qei for communicating with the QEI Server
Input
Parameters
qei_params the struct defines sensor type and resolution parameters for qei
Output
Returns
position from qei sensor in the range [0 - log(encoder_resolution)/log(2)]
valid for qei with index sensors: not valid - 0/ valid - 1 Get absolute position from QEI Server
Output channel c_qei for communicating with the QEI Server
 Output
Returns
counted up position from qei sensor (incorporates gear ratio) in the range [0 - encoder_resolution] * gear-ratio
direction of rotation, clockwise : 1 / anti-clockwise : -1 struct definition for velocity calculation from qei sensor
Function Documentation
int __qei_max_counts (int real_counts)
Internal function to calculate QEI position information.
Input qei counts per rotation
Output
Returns
max position from qei sensor
Definition at line 42 of file qei.c.
int get_qei_velocity (chanend c_qei, qei_par & qei_params, qei_velocity_par & qei_velocity_params)
Calculates the velocity from QEI sensor in 1 ms loop.
Output channel c_qei for communicating with the QEI Server
Input the struct defines sensor type and resolution parameters for qei struct for velocity calculation
Output
Returns
velocity from qei sensor in rpm
Referenced by _torque_ctrl(), and qei_test().
void init_qei_velocity_params (qei_velocity_par & qei_velocity_params)
Initialize struct for velocity calculation from QEI sensor.
Input struct is initialised
Definition at line 43 of file qei_client.xc.
References QEI_VELOCITY_PARAM::filter_buffer, QEI_VELOCITY_PARAM::filter_length, QEI_VELOCITY_PARAM::index, init_filter(), QEI_VELOCITY_PARAM::old_difference, and QEI_VELOCITY_PARAM::previous_position.
Referenced by _torque_ctrl(), commutation_sinusoidal_loop(), and qei_test().
void set_qei_sync_offset (chanend c_qei, int offset_forward, int offset_backward)
Internal function.
Internal function