sc_sncn_motoctrl_sin: sc_sncn_motorctrl_sin/module_blocks/src/filter_blocks/filter_blocks.h File Reference
filter_blocks.h File Reference
Functions
void init_filter (int filter_buffer[], int &index, int filter_length)
Initialise Moving Average Filter Parameters.
int filter (int filter_buffer[], int &index, int filter_length, int input)
Get moving average filtered output by passing the sampled data to be filtered as input.
int _modified_internal_filter (int filter_buffer[], int &index, int filter_length, int input)
Detailed Description
Moving Average Filter Implementation
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file filter_blocks.h.
Function Documentation
int _modified_internal_filter (int filter_buffer[], int & index, int filter_length, int input)
Definition at line 73 of file filter_blocks.xc.
Referenced by run_hall().
int filter (int filter_buffer[], int & index, int filter_length, int input)
Get moving average filtered output by passing the sampled data to be filtered as input.
Input
Parameters
filter_buffer
index
filter_length defines the length of the filter
input data sampled at fixed time
Output
Returns
filtered output
Definition at line 54 of file filter_blocks.xc.
Referenced by velocity_control().
void init_filter (int filter_buffer[], int & index, int filter_length)
Initialise Moving Average Filter Parameters.
Input
Parameters
filter_buffer array to initialized
index
filter_length defines the length of the filter
Definition at line 43 of file filter_blocks.xc.
Referenced by init_qei_velocity_params(), run_hall(), and velocity_control().