sc_sncn_ethercat: app_ethernet-demo/src/demo.xc File Reference
demo.xc File Reference
#include <xs1.h>
#include <xclib.h>
#include <print.h>
#include <platform.h>
#include <stdlib.h>
#include "otp_board_info.h"
#include "ethernet.h"
#include "checksum.h"
#include "xscope.h"
#include "ethercat.h"
Macros
#define USE_XSCOPE 0
#define OWN_IP_ADDRESS {192, 168, 0, 23}
#define ARP_RESPONSE 1
#define ICMP_RESPONSE 2
#define UDP_RESPONSE 3
#define MAX_BUFFER_SIZE 1024
Functions
void demo (chanend tx, chanend rx)
int is_ethertype (unsigned char data[], unsigned char type[])
int is_mac_addr (unsigned char data[], unsigned char addr[])
int is_broadcast (unsigned char data[])
int mac_custom_filter (unsigned int data[])
int build_arp_response (unsigned char rxbuf[], unsigned int txbuf[], const unsigned char own_mac_addr[6])
int is_valid_arp_packet (const unsigned char rxbuf[], int nbytes)
int build_icmp_response (unsigned char rxbuf[], unsigned char txbuf[], const unsigned char own_mac_addr[6])
int is_valid_icmp_packet (const unsigned char rxbuf[], int nbytes)
int main ()
Variables
unsigned char ethertype_ip [] = {0x08, 0x00}
unsigned char ethertype_arp [] = {0x08, 0x06}
unsigned char own_mac_addr [6]
Macro Definition Documentation
#define ARP_RESPONSE 1
Definition at line 69 of file demo.xc.
#define ICMP_RESPONSE 2
Definition at line 70 of file demo.xc.
#define MAX_BUFFER_SIZE 1024
Definition at line 418 of file demo.xc.
#define OWN_IP_ADDRESS {192, 168, 0, 23}
Definition at line 60 of file demo.xc.
Referenced by build_arp_response(), build_icmp_response(), is_valid_arp_packet(), and is_valid_icmp_packet().
#define UDP_RESPONSE 3
Definition at line 71 of file demo.xc.
#define USE_XSCOPE 0
Definition at line 34 of file demo.xc.
Function Documentation
int build_arp_response (unsigned char rxbuf[], unsigned int txbuf[], const unsigned char own_mac_addr[6])
Definition at line 126 of file demo.xc.
References OWN_IP_ADDRESS.
Referenced by demo().
int build_icmp_response (unsigned char rxbuf[], unsigned char txbuf[], const unsigned char own_mac_addr[6])
Definition at line 219 of file demo.xc.
References OWN_IP_ADDRESS.
Referenced by demo().
void demo (chanend tx, chanend rx)
Definition at line 369 of file demo.xc.
References build_arp_response(), build_icmp_response(), is_broadcast(), is_mac_addr(), is_valid_arp_packet(), is_valid_icmp_packet(), mac_custom_filter(), and own_mac_addr.
Referenced by main().
int is_broadcast (unsigned char data[])
Definition at line 103 of file demo.xc.
Referenced by demo().
int is_ethertype (unsigned char data[], unsigned char type[])
Definition at line 86 of file demo.xc.
Referenced by mac_custom_filter().
int is_mac_addr (unsigned char data[], unsigned char addr[])
Definition at line 92 of file demo.xc.
Referenced by demo().
int is_valid_arp_packet (const unsigned char rxbuf[], int nbytes)
Definition at line 170 of file demo.xc.
References OWN_IP_ADDRESS.
Referenced by demo().
int is_valid_icmp_packet (const unsigned char rxbuf[], int nbytes)
Definition at line 319 of file demo.xc.
References checksum_ip(), and OWN_IP_ADDRESS.
Referenced by demo().
int mac_custom_filter (unsigned int data[])
Definition at line 114 of file demo.xc.
References ethertype_arp, ethertype_ip, and is_ethertype().
Referenced by demo().
int main (void)
< CAN from module_ethercat to consumer
< CAN from consumer to module_ethercat
< Ethernet from module_ethercat to consumer
< Ethernet from consumer to module_ethercat
< Signals from EtherCAT to Ethernet MII
< File from module_ethercat to consumer
< File from consumer to module_ethercat
Definition at line 493 of file demo.xc.
References demo(), ecat_handler(), ecat_init(), and stdcore.
Variable Documentation
unsigned char ethertype_arp[] = {0x08, 0x06}
Definition at line 65 of file demo.xc.
Referenced by mac_custom_filter().
unsigned char ethertype_ip[] = {0x08, 0x00}
Definition at line 64 of file demo.xc.
Referenced by mac_custom_filter().
unsigned char own_mac_addr[6]
Definition at line 67 of file demo.xc.
Referenced by demo().